export const AUTH_REGISTER_START = "AUTH_REGISTER_START";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAIL = "AUTH_REGISTER_FAIL";

export const AUTH_LOGIN_START = "AUTH_LOGIN_START";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL";

export const AUTH_RESET_LOGIN = "AUTH_RESET_LOGIN";
export const AUTH_RESET_REGISTER = "AUTH_RESET_REGISTER";

export const AUTH_CHECK_TOKEN_START = "AUTH_CHECK_TOKEN_START";
export const AUTH_CHECK_TOKEN_SUCCESS = "AUTH_CHECK_TOKEN_SUCCESS";
export const AUTH_CHECK_TOKEN_FAIL = "AUTH_CHECK_TOKEN_FAIL";

export const ADV_CREATE_AD_START = "ADV_CREATE_AD_START";
export const ADV_CREATE_AD_SUCCESS = "ADV_CREATE_AD_SUCCESS";
export const ADV_CREATE_AD_FAIL = "ADV_CREATE_AD_FAIL";

export const ADV_RESET_MODAL_FORM = "ADV_RESET_MODAL_FORM";


export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const AUTH_ROLES = "AUTH_ROLES";

export const ADV_GET_ADS = "ADV_GET_ADS";

export const ADV_FILTER_ADS = "ADV_FILTER_ADS";

export const ADV_UPLOAD = "ADV_UPLOAD";

export const ADV_GET_AD = "ADV_GET_AD";

export const ADV_CREATE_REVIEW = "ADV_CREATE_REVIEW";

export const ADV_GET_COMMENTS = "ADV_GET_COMMENTS";

export const ADV_GET_MYAD = "ADV_GET_MYAD";

export const AUTH_CHANGE_NAME_SURNAME_START = "AUTH_CHANGE_NAME_SURNAME_START";
export const AUTH_CHANGE_NAME_SURNAME_SUCCESS = "AUTH_CHANGE_NAME_SURNAME_SUCCESS";
export const AUTH_CHANGE_NAME_SURNAME_FAIL = "AUTH_CHANGE_NAME_SURNAME_FAIL";

export const AUTH_CHANGE_EMAIL_START = "AUTH_CHANGE_EMAIL_START";
export const AUTH_CHANGE_EMAIL_SUCCESS = "AUTH_CHANGE_EMAIL_SUCCESS";
export const AUTH_CHANGE_EMAIL_FAIL = "AUTH_CHANGE_EMAIL_FAIL";

export const AUTH_CHANGE_PASSWORD_START = "AUTH_CHANGE_PASSWORD_START";
export const AUTH_CHANGE_PASSWORD_SUCCESS = "AUTH_CHANGE_PASSWORD_SUCCESS";
export const AUTH_CHANGE_PASSWORD_FAIL = "AUTH_CHANGE_PASSWORD_FAIL";

export const ADV_GET_ADS_ADMIN = "ADV_GET_ADS_ADMIN";

export const ADV_CHANGE_APPROVED_SUCCES = "ADV_CHANGE_APPROVED_SUCCES";

export const ADV_DELETE_ADS = "ADV_DELETE_ADS";

export const AUTH_GET_USERS = "AUTH_GET_USERS";

export const AUTH_DELETE_USER = "AUTH_DELETE_USER";

export const AUTH_GET_ME = "AUTH_GET_ME";

export const AUTH_GET_ME_LOADING = "AUTH_GET_ME_LOADING";

export const AUTH_SET_ADMIN = "AUTH_SET_ADMIN";

export const AUTH_GET_ADMINS = "AUTH_GET_ADMINS";

export const ADV_UPDATE_COMMENT = "ADV_UPDATE_COMMENT";

export const ADV_GET_COMMENTS_LOADING = "ADV_GET_COMMENTS_LOADING";



