export const AUTH_REGISTER_START = "AUTH_REGISTER_START";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAIL = "AUTH_REGISTER_FAIL";

export const AUTH_LOGIN_START = "AUTH_LOGIN_START";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL";

export const AUTH_RESET_LOGIN = "AUTH_RESET_LOGIN";
export const AUTH_RESET_REGISTER = "AUTH_RESET_REGISTER";

export const AUTH_CHECK_TOKEN_START = "AUTH_CHECK_TOKEN_START";
export const AUTH_CHECK_TOKEN_SUCCESS = "AUTH_CHECK_TOKEN_SUCCESS";
export const AUTH_CHECK_TOKEN_FAIL = "AUTH_CHECK_TOKEN_FAIL";
